### ISSUE TITLE
关于CustomNuScenesDataset里的results_save_total.pk

### ISSUE THREAD

**Issue by xsxyh** [nullmax-vision/QAF2D#1]
作者你好，请问文件projects/mmdet3d_plugin/datasets/results_save_total.pkl'是怎么生成的，目前开源代码里的该文件似乎有问题，无法正常读取，方便的话希望能重新提供该文件。
![Snipaste_2024-10-15_17-40-09](https://github.com/user-attachments/assets/b1dfef9e-b755-42a6-aa20-87aec2c1bc20)

**Comment by jin-yc10** [comment]
This seems to be a file handled by git lfs. You may setup git-lfs on your machine, then
```bash
git lfs install
git lfs pull
```
